// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

// 
// app/javascript/controllers/index.js
// app/javascript/controllers/index.js
import { application } from "controllers/application"

import HelloController from "controllers/hello_controller"
application.register("hello", HelloController)

import MenuController from "controllers/menu_controller"
application.register("menu", MenuController)

import RemovableController from "controllers/removable_controller"
application.register("removable", RemovableController)

import SubmitController from "controllers/submit_controller"
application.register("submit", SubmitController)

import ToggleController from "controllers/toggle_controller"
application.register("toggle", ToggleController)

import VideoPreviewController from "controllers/video_preview_controller"
application.register("video-preview", VideoPreviewController)
